#!/bin/bash

# Get the directory of the script
SCRIPT_DIR=$(dirname "$0")

python3 $SCRIPT_DIR/scorpion.sif --preprocess $@ \
  --search "astar(scp_online([projections(sys_scp(
        max_time=100, max_time_per_restart=10, max_pdb_size=2M, max_collection_size=20M,
        pattern_type=interesting_non_negative, create_complete_transition_system=true),
      create_complete_transition_system=true)],
    saturator=perimstar, max_time=100, max_size=1M, interval=10K, orders=greedy_orders()))"
